# Generated by Django 6.0.2 on 2026-03-18 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_book_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'get_latest_by': '-created_at',
            },
        ),
        migrations.RemoveConstraint(
            model_name='book',
            name='book_title_category_unq_cst',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_title_category_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'FANTASY CATEGORY'), ('Mystic', 'MYSTIC CATEGORY'), ('Biography', 'BIOGRAPHY CATEGORY'), ('Science', 'SCIENCE CATEGORY'), ('Fiction', 'FICTION CATEGORY'), ('Science Fiction', 'SCIENCE FICTION CATEGORY'), ('Horror', 'HORROR CATEGORY'), ('Detective', 'DETECTIVE CATEGORY'), ('Romance', 'ROMANCE CATEGORY'), ('N/A', 'UNRECOGNISED CATEGORY')], default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
