# Generated by Django 6.0.2 on 2026-03-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_category_remove_book_book_title_category_unq_cst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'category'], name='book_title_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='book_title_category_unq_cst'),
        ),
    ]
